/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dbService_constants.h"

namespace DSSE {

const dbServiceConstants g_dbService_constants;

dbServiceConstants::dbServiceConstants() {
}

} // namespace

