/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dbService_CONSTANTS_H
#define dbService_CONSTANTS_H

#include "dbService_types.h"

namespace DSSE {

class dbServiceConstants {
 public:
  dbServiceConstants();

};

extern const dbServiceConstants g_dbService_constants;

} // namespace

#endif
