// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "dbService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::DSSE;

class dbServiceHandler : virtual public dbServiceIf {
 public:
  dbServiceHandler() {
    // Your initialization goes here
  }

  int32_t queryWord(const std::string& trapdoor, const std::string& key, const std::string& left) {
    // Your implementation goes here
    printf("queryWord\n");
  }

  void addWord(const std::string& key, const std::string& value) {
    // Your implementation goes here
    printf("addWord\n");
  }

  void addWords(const std::vector<std::string> & keys, const std::vector<std::string> & values) {
    // Your implementation goes here
    printf("addWords\n");
  }

  void deleteWord(const std::string& trapdoor, const std::string& delTrapdoor, const std::string& key) {
    // Your implementation goes here
    printf("deleteWord\n");
  }

  void deleteWords(const std::vector<std::string> & trapdoors, const std::vector<std::string> & keys) {
    // Your implementation goes here
    printf("deleteWords\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<dbServiceHandler> handler(new dbServiceHandler());
  shared_ptr<TProcessor> processor(new dbServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

